import type { CatalogFamily, CatalogProduct } from "@/lib/catalog-types";

const PRODUCTS: CatalogProduct[] = [
  {
    id: "prd-elq-alf-001",
    sku: "ELQ-ALFA-CLASS-10",
    slug: "classic-blend-10ml-alfaliquid",
    name: "Classic Blend 10ml",
    shortDescription: "Profil tabac sec, simple et regulier.",
    longDescription: "E-liquide fictif pour demarrage MTL avec rendu sec et discret.",
    family: "E_LIQUID",
    type: "E_LIQUID",
    brandName: "Alfaliquid",
    brandSlug: "alfaliquid",
    categoryName: "E-liquides",
    categorySlug: "e-liquides",
    priceCents: 590,
    stockPolicy: "FINITE",
    stockQty: 60,
    tags: ["classic", "mtl", "debutant"],
    imageUrl: "/product-placeholder.svg",
    warningRequired: true,
    nicotineMg: 6,
    pgRatio: 50,
    vgRatio: 50,
    volumeMl: 10
  },
  {
    id: "prd-elq-vdlv-002",
    sku: "ELQ-VDLV-FRUIT-10",
    slug: "fruit-sec-10ml-vdlv",
    name: "Fruit Sec 10ml",
    shortDescription: "Note fruitee legere, sans exces sucre.",
    longDescription: "E-liquide fictif oriente clarte aromatique pour tirage indirect.",
    family: "E_LIQUID",
    type: "E_LIQUID",
    brandName: "VDLV",
    brandSlug: "vdlv",
    categoryName: "E-liquides",
    categorySlug: "e-liquides",
    priceCents: 620,
    stockPolicy: "FINITE",
    stockQty: 55,
    tags: ["fruit", "mtl"],
    imageUrl: "/product-placeholder.svg",
    warningRequired: true,
    nicotineMg: 3,
    pgRatio: 60,
    vgRatio: 40,
    volumeMl: 10
  },
  {
    id: "prd-elq-trv-003",
    sku: "ELQ-TERROIR-NATURE-10",
    slug: "nature-equilibre-10ml-terroir-vapeur",
    name: "Nature Equilibre 10ml",
    shortDescription: "Base neutre et ronde pour usage quotidien.",
    longDescription: "E-liquide fictif axe regularite et faible echauffement.",
    family: "E_LIQUID",
    type: "E_LIQUID",
    brandName: "Terroir Vapeur",
    brandSlug: "terroir-vapeur",
    categoryName: "E-liquides",
    categorySlug: "e-liquides",
    priceCents: 640,
    stockPolicy: "FINITE",
    stockQty: 42,
    tags: ["equilibre", "mtl"],
    imageUrl: "/product-placeholder.svg",
    warningRequired: true,
    nicotineMg: 6,
    pgRatio: 50,
    vgRatio: 50,
    volumeMl: 10
  },
  {
    id: "prd-elq-vgt-004",
    sku: "ELQ-VEGETOL-DOUX-10",
    slug: "doux-vegetal-10ml-vegetol",
    name: "Doux Vegetal 10ml",
    shortDescription: "Sensation douce pour tirage indirect.",
    longDescription: "E-liquide fictif formule pour une sensation plus legere en gorge.",
    family: "E_LIQUID",
    type: "E_LIQUID",
    brandName: "Vegetol",
    brandSlug: "vegetol",
    categoryName: "E-liquides",
    categorySlug: "e-liquides",
    priceCents: 690,
    stockPolicy: "FINITE",
    stockQty: 35,
    tags: ["doux", "mtl", "quotidien"],
    imageUrl: "/product-placeholder.svg",
    warningRequired: true,
    nicotineMg: 6,
    pgRatio: 40,
    vgRatio: 60,
    volumeMl: 10
  },
  {
    id: "prd-elq-cur-005",
    sku: "ELQ-CURIEUX-FRAIS-10",
    slug: "frais-modere-10ml-curieux",
    name: "Frais Modere 10ml",
    shortDescription: "Sensation fraiche moderee, non agressive.",
    longDescription: "E-liquide fictif pense pour conserver un tirage MTL confortable.",
    family: "E_LIQUID",
    type: "E_LIQUID",
    brandName: "Curieux",
    brandSlug: "curieux",
    categoryName: "E-liquides",
    categorySlug: "e-liquides",
    priceCents: 650,
    stockPolicy: "FINITE",
    stockQty: 48,
    tags: ["frais", "mtl"],
    imageUrl: "/product-placeholder.svg",
    warningRequired: true,
    nicotineMg: 3,
    pgRatio: 50,
    vgRatio: 50,
    volumeMl: 10
  },
  {
    id: "prd-elq-sav-006",
    sku: "ELQ-SAVOUREA-CLASSIC-10",
    slug: "classic-doux-10ml-savourea",
    name: "Classic Doux 10ml",
    shortDescription: "Classic leger adapte au MTL debutant.",
    longDescription: "E-liquide fictif de reference pour parcours d initiation adulte.",
    family: "E_LIQUID",
    type: "E_LIQUID",
    brandName: "Savourea",
    brandSlug: "savourea",
    categoryName: "E-liquides",
    categorySlug: "e-liquides",
    priceCents: 580,
    stockPolicy: "FINITE",
    stockQty: 70,
    tags: ["classic", "debutant", "mtl"],
    imageUrl: "/product-placeholder.svg",
    warningRequired: true,
    nicotineMg: 12,
    pgRatio: 70,
    vgRatio: 30,
    volumeMl: 10
  },
  {
    id: "prd-mod-lvt-007",
    sku: "MTL-MOD-CORE-01",
    slug: "core-mtl-mod-20w",
    name: "Core MTL Mod 20W",
    shortDescription: "Mod compact faible puissance pour MTL.",
    longDescription: "Materiel fictif simple a regler avec puissance moderee.",
    family: "MTL_MATERIAL",
    type: "MTL_MOD",
    brandName: "LovaTech",
    brandSlug: "lovatech",
    categoryName: "Materiel MTL",
    categorySlug: "materiel-mtl",
    priceCents: 3290,
    stockPolicy: "FINITE",
    stockQty: 18,
    tags: ["mod", "mtl", "20w"],
    imageUrl: "/product-placeholder.svg",
    warningRequired: true,
    recommendedPowerMinW: 8,
    recommendedPowerMaxW: 20,
    airflowStyle: "indirect",
    connectorType: "510",
    resistanceRange: "0.8-1.8 ohm"
  },
  {
    id: "prd-mod-lvt-008",
    sku: "MTL-MOD-LITE-02",
    slug: "lite-mtl-mod-18w",
    name: "Lite MTL Mod 18W",
    shortDescription: "Format leger pour usage quotidien.",
    longDescription: "Materiel fictif oriente autonomie moderee et simplicite.",
    family: "MTL_MATERIAL",
    type: "MTL_MOD",
    brandName: "LovaTech",
    brandSlug: "lovatech",
    categoryName: "Materiel MTL",
    categorySlug: "materiel-mtl",
    priceCents: 2890,
    stockPolicy: "FINITE",
    stockQty: 21,
    tags: ["mod", "mtl", "compact"],
    imageUrl: "/product-placeholder.svg",
    warningRequired: true,
    recommendedPowerMinW: 7,
    recommendedPowerMaxW: 18,
    airflowStyle: "indirect",
    connectorType: "510",
    resistanceRange: "1.0-1.8 ohm"
  },
  {
    id: "prd-clr-lvt-009",
    sku: "MTL-CLEARO-FOCUS-01",
    slug: "focus-mtl-clearomiseur",
    name: "Focus MTL Clearomiseur",
    shortDescription: "Tirage serre avec airflow progressif.",
    longDescription: "Clearomiseur fictif dedie au tirage indirect et basse puissance.",
    family: "MTL_MATERIAL",
    type: "MTL_CLEAROMIZER",
    brandName: "LovaTech",
    brandSlug: "lovatech",
    categoryName: "Materiel MTL",
    categorySlug: "materiel-mtl",
    priceCents: 2190,
    stockPolicy: "FINITE",
    stockQty: 24,
    tags: ["clearo", "mtl", "airflow"],
    imageUrl: "/product-placeholder.svg",
    warningRequired: true,
    recommendedPowerMinW: 10,
    recommendedPowerMaxW: 17,
    airflowStyle: "serre",
    connectorType: "510",
    resistanceRange: "1.0-1.6 ohm"
  },
  {
    id: "prd-clr-lvt-010",
    sku: "MTL-CLEARO-BALANCE-02",
    slug: "balance-mtl-clearomiseur",
    name: "Balance MTL Clearomiseur",
    shortDescription: "Rendu saveur stable pour faibles puissances.",
    longDescription: "Clearomiseur fictif base sur un usage modere et regulier.",
    family: "MTL_MATERIAL",
    type: "MTL_CLEAROMIZER",
    brandName: "LovaTech",
    brandSlug: "lovatech",
    categoryName: "Materiel MTL",
    categorySlug: "materiel-mtl",
    priceCents: 2390,
    stockPolicy: "FINITE",
    stockQty: 16,
    tags: ["clearo", "mtl", "saveur"],
    imageUrl: "/product-placeholder.svg",
    warningRequired: true,
    recommendedPowerMinW: 9,
    recommendedPowerMaxW: 16,
    airflowStyle: "indirect",
    connectorType: "510",
    resistanceRange: "0.8-1.4 ohm"
  }
];

export function getAllCatalogProducts(): CatalogProduct[] {
  return PRODUCTS;
}

export function getCatalogProductsByFamily(family: CatalogFamily): CatalogProduct[] {
  return PRODUCTS.filter((product) => product.family === family);
}

export function getCatalogProductBySlug(slug: string): CatalogProduct | undefined {
  return PRODUCTS.find((product) => product.slug === slug);
}

